from django.conf.urls import patterns, url

urlpatterns = patterns(
    'photo_manager.views',
    url(r'^$',
        'home_view',
        name='home'),
    url(r'^login/$',
        'LOGIN',
        name='login'),
    url(r'^logout/$',
        'LOGOUT',
        name='logout'),
    url(r'^activate/complete/$',
        'ACTIVATION_COMPLETE',
        name='registration_activation_complete'),
    url(r'^album/(\d+)/$',
        'album_view',
        name='album'),
    url(r'^photo/(\d+)/(\d+)/$',
        'photo_detail_view',
        name='photo'),
    url(r'^create/$',
        'create_album_view',
        name='create'),
    url(r'^edit/(\d+)/$',
        'edit_album_view',
        name='edit_album'),
    url(r'^314159265358979323846264/delete/(\d+)/$',
        'delete_album_view',
        name='delete_album'),
    url(r'^edit/(\d+)/(\d+)/$',
        'edit_photo_view',
        name='edit_photo'),
    url(r'^314159265358979323846264/delete/(\d+)/(\d+)/$',
        'delete_photo_view',
        name='delete_photo'),
    )
